stages:
  - build
  - deploy

build_job:
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy_job:
  stage: deploy
  script:
  - deploy
  only:
  - master
