stages:
  - build
  - deploy

build_job:
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy_job:
  stage: deploy
  script:
  - rsync -avz public/ victoria@victoriarozhina.us:/var/www/victoriarozhina.us/html/
  only:
  - master
