stages:
  - build
  - deploy

build_job:
  stage: build
  tags:
  - blog
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy_job:
  stage: deploy
  tags:
  - blog
  script:
  - ./deploy
  only:
  - master
