baseURL = "http://victoriarozhina.pages.gitlab.victoriarozhina.us/personal-blog/"
languageCode = "en-us"
title = "Victoria's blog"
theme = "victoria_theme"

[permalinks]
  about = "/:filename/"
  page = "/:title/"
  post = "/:year/:month/:day/:title/"
